version: '3'

services:
  server:
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      - cache

  cache:
    image: memcached
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64
